# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/20_hs_ad_da/hs_ad_da.srcs/sources_1/ip/rom_wave_sawtooth/rom_wave_sawtooth.xci
# IP: The module: 'rom_wave_sawtooth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/20_hs_ad_da/hs_ad_da.srcs/sources_1/ip/rom_wave_sawtooth/rom_wave_sawtooth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_wave_sawtooth'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/20_hs_ad_da/hs_ad_da.srcs/sources_1/ip/rom_wave_sawtooth/rom_wave_sawtooth.xci
# IP: The module: 'rom_wave_sawtooth' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/20_hs_ad_da/hs_ad_da.srcs/sources_1/ip/rom_wave_sawtooth/rom_wave_sawtooth_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom_wave_sawtooth'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
