# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/hs_ad_da.xdc

# IP: ip/clk_wiz_pixel/clk_wiz_pixel.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_pixel || ORIG_REF_NAME==clk_wiz_pixel} -quiet] -quiet
