# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.cache/wt [current_project]
set_property parent.project_path D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/IP_Users [current_project]
update_ip_catalog
set_property ip_output_repo d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/doc/dds_256x8b_wave.coe
add_files D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/doc/wave_triangular.coe
add_files D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/doc/wave_sawtooth.coe
add_files D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/doc/wave_sawtooth_16.coe
read_verilog -library xil_defaultlib {
  D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/new/ad_wave_rec.v
  D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/new/da_wave_send.v
  D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/new/dry_grid.v
  D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/new/dry_waveform.v
  D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/new/video_driver.v
  D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/new/hs_ad_da.v
}
read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.xci
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel_board.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/clk_wiz_pixel/clk_wiz_pixel_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_0/ila_0.xci
set_property used_in_synthesis false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_0/ila_0_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rom_256x8b/rom_256x8b.xci
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rom_256x8b/rom_256x8b_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_grid/ila_grid.xci
set_property used_in_synthesis false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_grid/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_grid/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_grid/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_grid/ila_grid_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_bram_dataput/ila_bram_dataput.xci
set_property used_in_synthesis false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_bram_dataput/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_bram_dataput/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_bram_dataput/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_bram_dataput/ila_bram_dataput_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_ram_datain/ila_ram_datain.xci
set_property used_in_synthesis false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_ram_datain/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_ram_datain/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_ram_datain/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/ila_ram_datain/ila_ram_datain_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rom_wave_triangular/rom_wave_triangular.xci
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rom_wave_triangular/rom_wave_triangular_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rom_wave_sawtooth/rom_wave_sawtooth.xci
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/rom_wave_sawtooth/rom_wave_sawtooth_ooc.xdc]

read_ip -quiet D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/vio_wave_select/vio_wave_select.xci
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/vio_wave_select/vio_wave_select.xdc]
set_property used_in_implementation false [get_files -all d:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/sources_1/ip/vio_wave_select/vio_wave_select_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/constrs_1/new/hs_ad_da.xdc
set_property used_in_implementation false [get_files D:/Desktoop/Studio_FPGA/DD1_AD_DA_HDMI/Project_Code/hs_ad_da.srcs/constrs_1/new/hs_ad_da.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top hs_ad_da -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef hs_ad_da.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file hs_ad_da_utilization_synth.rpt -pb hs_ad_da_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
